export const FOLLOWERS = [
  {
    id: 1,
    photo: "",
    name: "Shah Rukh Khan",
    username: "@srk",
    isFollowing: false,
  },
  {
    id: 2,
    photo: "",
    name: "Robert Downey Jr.",
    username: "@rdj",
    isFollowing: true,
  },
  {
    id: 3,
    photo: "",
    name: "Tom Cruise",
    username: "@tomcruise",
    isFollowing: false,
  },
  {
    id: 4,
    photo: "",
    name: "Elezabeth",
    username: "@elezabeth",
    isFollowing: false,
  },
  {
    id: 5,
    photo: "",
    name: "Kate Winslet",
    username: "@KateWinslet",
    isFollowing: false,
  },
  {
    id: 6,
    photo: "",
    name: "Shah Rukh Khan",
    username: "@srk",
    isFollowing: false,
  },
  {
    id: 7,
    photo: "",
    name: "Robert Downey Jr.",
    username: "@rdj",
    isFollowing: true,
  },
  {
    id: 8,
    photo: "",
    name: "Tom Cruise",
    username: "@tomcruise",
    isFollowing: false,
  },
  {
    id: 9,
    photo: "",
    name: "Elezabeth",
    username: "@elezabeth",
    isFollowing: false,
  },
  {
    id: 10,
    photo: "",
    name: "Kate Winslet",
    username: "@KateWinslet",
    isFollowing: false,
  },
];